- name: varaible from vars vars_files
  hosts: localhost
  connection: local
  vars_files:
  - vars.yaml
  become: yes

  tasks:
  - 
    ansible.builtin.package:
      name: "{{package}}"
      state: present