- name: loops
  hosts: localhost
  connection: local
  
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Jani
    - Haseena
    - Muneer
    - Azmath