- name: variables
  hosts: web
  vars:
    COURSE: "DEVOPS with AZURE"
    NAME: "Muneer"

  tasks:
   - name: print the info
  vars: 
    COURSE: "DEVOPS"
    ansible.builtin.debug:
      msg: "{{NAME}} is learning {{COURSE}} with ansible"