- name: conditions
  hosts: local
  connection: local
  var_prompt:
  - name: number
    prompt: Please enter the number
    private: false
  tasks:
  - name: big or small
    ansible.builtin.debug:
      msg: "Given numer {{ number }} is less then 10"    
    when: number < 10
  
  - name: big
    ansible.builtin.debug:
      msg: " Given number {{ number }} is bigger then 10"
    when: number > 10

