- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: Print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ COURSE | default('Ansible') }}"
      msg: "Hello {{ Name | default('Muneer') }}"

  - name: convert to upparcase
    vars:
      greeting: "Hello Muneer"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: lower case
    vars:
      greeting: " Hello Muneer"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"


