- name: cmd vs Shell
  hosts: local
  connection: local
  tasks:
  - ame: execute cmd and shell in ansible
    # ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt 
