---
- name: creating ec2 and updtaing r53
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0539f15784b4ea646
    sg_id: sg-0670763c62c77ba9b
    ami_id: ami-09c813fb71547fc4f
    type: t3.micro
    instances:
      - mysql
      - backend
      - frontend
    zone: mxyz.shop
  tasks:
    - name: create ec2
      amazon.aws.ec2_instance:
        name: "{{item}}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ type }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances
    - name: print output
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"
    - name: create r53 records
      amazon.aws.route53: null
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      override: true
      loop: "{{ ec2_instances.results }}"
